name: 'EESSI'
description: 'Install the EESSI software stack.'
branding:
  icon: 'server'
  color: 'gray-dark'
inputs:
  eessi_stack_version:
    description: 'Version of the EESSI stack to configure'
    required: false
    default: '2023.06'

runs:
  using: "composite"
  steps:
    - uses: cvmfs-contrib/github-action-cvmfs@55899ca74cf78ab874bdf47f5a804e47c198743c # v4.0
      with:
        cvmfs_config_package: https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi_latest_all.deb
        cvmfs_http_proxy: DIRECT
        cvmfs_repositories: software.eessi.io
    - id: install-eessi
      run: |
        echo "EESSI_SILENT=1" >> $GITHUB_ENV
        echo 'unset BASH_ENV' >> $HOME/env_config.export
        echo "source /cvmfs/software.eessi.io/versions/$EESSI_STACK_VERSION/init/bash" >> $HOME/env_config.export
        sudo apt install -y direnv
        echo 'eval "$(direnv export bash)"' >> $HOME/env_config.export
        mkdir -p $HOME/direnv/
        echo "[whitelist]" >> $HOME/direnv/direnv.toml
        echo "prefix = [ '$GITHUB_WORKSPACE' ]" >> $HOME/direnv/direnv.toml
        cp $HOME/direnv/direnv.toml $HOME/direnv/config.toml
        echo "BASH_ENV=$HOME/env_config.export" >> $GITHUB_ENV
        echo "DIRENV_CONFIG=$HOME/direnv" >> $GITHUB_ENV
      shell: bash
      env:
        EESSI_STACK_VERSION: ${{ inputs.eessi_stack_version }}
