name: Bump version tags
on:
  release:
    types:
      - "created"
# Declare default permissions as read only.
permissions: read-all
jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '0'
      - uses: robinraju/release-downloader@589f66e0b743641255594babae37479abb67e825 # v1.12 + node24 support
        with:
          repository: "fischerscode/tagger"
          fileName: "tagger.linux"
          tag: v0.1.0
      - run: |
          # Make sure the tagger is what we expect
          echo "efe6d66750425757e599e586b995a19868e0f6b87428c872abce541df423f9d2 tagger.linux"|sha256sum --check --status
      - run: |
          chmod +x $GITHUB_WORKSPACE/tagger.linux
          $GITHUB_WORKSPACE/tagger.linux move -s -p 'v' ${RELEASE_TAG##*/}
          rm $GITHUB_WORKSPACE/tagger.linux
          repo="https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "$repo" --tags --force
        shell: bash
        env:
          TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ github.ref }}
