name: macOS-minimal
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Declare default permissions as read only.
permissions: read-all
jobs:
  macOS-minimal:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ./
    # - name: Test EESSI
    #  run: |
    #    direnv status
    #    module avail
    #  shell: bash
    - name: Test available repos
      run: |
        ls /cvmfs/software.eessi.io
        ls /cvmfs/dev.eessi.io
      shell: bash
