name: ubuntu-minimal_usage
on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Declare default permissions as read only.
permissions: read-all
jobs:
  minimal_usage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
          - ubuntu-latest
        eessi_version:
          - 2023.06
          - 2025.06
          - 2026.06
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: ./
      with:
          eessi_stack_version: ${{ matrix.eessi_version }}
    - name: Test EESSI
      run: |
        direnv status
        module avail
      shell: bash
    - name: Test available repos
      run: |
        # Make sure an EESSI module is loaded
        module list |& grep "EESSI/"
        ls /cvmfs/software.eessi.io
        ls /cvmfs/dev.eessi.io
      shell: bash

  test_mount_only:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ./
      with:
        mount_cvmfs_only: 'true'
        init_direnv: 'false'
    - name: Test EESSI not initialised
      run: |
        if [[ -v EESSI_VERSION ]]; then
          echo "EESSI_VERSION should not be set as this indicates EESSI is initialised"
          exit 1
        fi
        # Make sure CVMFS is mounted, and EESSI available
        ls /cvmfs/software.eessi.io
      shell: bash
