name: ubuntu-minimal_usage-bash_script_init
on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Declare default permissions as read only.
permissions: read-all
jobs:
  minimal_usage_bash_script:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04-arm
          - ubuntu-24.04
          - ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ./
      with:
        use_eessi_module: false
        init_direnv: false
    - name: Test EESSI
      run: |
        module avail
        if ! module list |& grep -q "EESSI/"; then
          echo "EESSI module is NOT loaded"
        else
          echo "EESSI module is loaded but shouldn't be"
          exit 1
        fi
      shell: bash
    - name: Test available repos
      run: |
        ls /cvmfs/software.eessi.io
        ls /cvmfs/dev.eessi.io
      shell: bash
