name: ubuntu-minimal_usage
on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# Declare default permissions as read only.
permissions: read-all
jobs:
  minimal_usage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04-arm
          - os: ubuntu-24.04
          - os: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - uses: ./
    - name: Test EESSI
      run: |
        direnv status
        module avail
      shell: bash
    - name: Test available repos
      run: |
        ls /cvmfs/software.eessi.io
        ls /cvmfs/dev.eessi.io
      shell: bash
